language: java
jdk:
- oraclejdk8
dist: trusty
script:
- mvn verify
after_success:
- mvn coveralls:report
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_BRANCH}" != "master" && mvn deploy --settings travis/settings.xml
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - "/^bullet-kafka-[0-9]+\\.[0-9]+\\.[0-9]+/"
env:
  global:
  - secure: yPaQgohO62OW0PNWhyN7gJ6euvWdWcbX0nv7DHP6fhny0gp7kjv3SejXR0D+qKjXd5hxBw1Klw3PUu+z9dGSwQrqHs7hHvS+YDdzfObAM62EMt4JcOtXX4C0XexDpFqDTfam1yA10r5NY4YPuM7Q0CpE1U6suwTo65FjheBwpbOqgdzMLAawIZyRen8rUz7VnMoy86WFTKMOWgrbPTxza2NkETu1qEAcBA1Fjeb/esZF3QHjiwUamkhA0NrM5Xxgyw/z42ieLCt8W0718JYPd4sozKlXRbGTtCqBoUrrGXyvJRvMXow3/k81zTp2leOrGDbpLXX5mINYOBBfr0x2rPKznUlzZDb2Jf9FSG2BQ03KiACsP2TKOuxtdJRxVLv5qjffTp1hP/ZoSkOi0/AAyZJ+3Wx4Ojg1ecTcVwrrB20NGhyg6tph7tnAi54b+XH99Hk4g+EqLJHFsZ0Pl7ZGTew98EZaqpE++vZIjQgxZffBDmrJvwD1eis7kRXrAr3x/UJp8e6Zxk5ZwRQVgeGxNr7awd7ND0Sl04mOeVwTAeZQni7FMZkepCSaTY6XHdsDeuU5SrFCnpsGjzWmddmNdFCDCG1SgXaNpqB7Ki4dEJW7DZ9w41i2wLiEiOVTNZgKUA98MfOx5PGJM13DRZtKaHzovmRgrv5KQTHKVFzPG9I=
  - secure: tVTbv0wk4s+C15c9AAWu+qoecy9dVapnJEmbIM6i39/ocmBVSc6nr0iqLIAn91bLMMbmp6H0Y7866SHZwnwVq51Auhi0AErec5W2l24jRz4WJAcznDykfSSHeZj0FGmcmn41cB9cWvinakEFyjLhdv00DkpQFbkN68eZuaJyN5r2hFEDRHNvOLzeP4EBP0g6k8Gy6LKvbifTnfu/7YSzU2rTs1vAH8NRcilSLzv58UFfMyN4whVp6XdARA5zLd5FF3PBlWvrJCqv3dMR8dZNvzXtKXEuf67xE5ZsGBqzej8VqjRt5tCtFBVH9YwE9qcUutWGlWeHtSkCuXKGIPVJNX1zPscsW4KSPsY8rYdqbD9wTgAv/0WhbRVcHlDFiLthi2thP3k7BcPCeV6spBynO1Pd404LqF3jWvbdOeVH9kpstKRTNWHUERwQ1gqEJbsMA+4uUtAquCoMmUrPveebmV1/QUo0Uo6vBej1V224klSvFgTVptzAVlHLxyjn9aObal3B/awM4DihZHZliUTRt3J1pwB/3B39gXCMkB1WuqgHT0kU4UBczybzlT5SxdMP27vfP3uSk45zYoT/xRS1kPQDGecvJp5AvKXWn5/CtH+vLmr6y+cEAGRYEyecO68NfmXvAbMY91Huj8Fxi1zCoYW+AF6wG297cN7dyPRJvAo=
